CREATE TABLE `appointment_satisfactions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `appointment_id` bigint unsigned NOT NULL,
  `patient_id` bigint unsigned NULL,
  `professional_id` bigint unsigned NULL,
  `service_id` bigint unsigned NULL,
  `token` varchar(80) NOT NULL,
  `rating` tinyint unsigned NULL,
  `comment` text NULL,
  `patient_name` varchar(255) NULL,
  `patient_dni` varchar(30) NULL,
  `patient_phone` varchar(40) NULL,
  `professional_name` varchar(255) NULL,
  `service_description` varchar(255) NULL,
  `appointment_date` date NULL,
  `sent_at` timestamp NULL,
  `answered_at` timestamp NULL,
  `created_at` timestamp NULL,
  `updated_at` timestamp NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `appointment_satisfactions_appointment_id_unique` (`appointment_id`),
  UNIQUE KEY `appointment_satisfactions_token_unique` (`token`),
  KEY `appt_satisfaction_report_idx` (`appointment_date`, `professional_id`, `service_id`, `rating`),
  KEY `appointment_satisfactions_patient_id_foreign` (`patient_id`),
  KEY `appointment_satisfactions_professional_id_foreign` (`professional_id`),
  CONSTRAINT `appointment_satisfactions_appointment_id_foreign` FOREIGN KEY (`appointment_id`) REFERENCES `appointments` (`id`) ON DELETE CASCADE,
  CONSTRAINT `appointment_satisfactions_patient_id_foreign` FOREIGN KEY (`patient_id`) REFERENCES `patients` (`id`) ON DELETE SET NULL,
  CONSTRAINT `appointment_satisfactions_professional_id_foreign` FOREIGN KEY (`professional_id`) REFERENCES `professionals` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
